---
services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:5.1
    restart: always
    ports:
      - 8081:8080
    environment:
      PBF_URL: https://download.geofabrik.de/europe/hungary-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/hungary-updates/
      NOMINATIM_PASSWORD: terkepeszet
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    shm_size: 1gb
  photon:
    build:
      context: ./photon
      dockerfile: Dockerfile
    depends_on:
      - nominatim
    volumes:
      - photon-data:/photon/photon_data
    ports:
      - 2322:2322
    restart: always
volumes:
  nominatim-data: null
  photon-data: null
